### ISSUE TITLE
Problem: staked state jailed, but slash amount is 0

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1045]
Discovered by @lezzokafka on 0.2.1. Not sure how to exactly reproduce it, but it went something like this:

* a validator joined with a wrong name --> he then unbonded most of its stake (maybe all), withdrew, deposited to a new staked state and submitted a node join again with that new staked state (not sure if the same consensus pub key or different -- to be confirmed)
* the old state (`0x42a48fcfd623d891a22325b89c920e31d50ef604`) was jailed, has some small amount in unbonded (1.60.... perhaps not withdrawing all?) and slash amount as 0.00000000

**Comment by tomtau** [comment]
perhaps due to decimal places in Milli? also not sure why jailed for non-live -- the tracking information should have been removed in 0.2.1: https://github.com/crypto-com/chain/blob/release/v0.2/chain-abci/src/app/end_block.rs#L174 ?

**Comment by lezzokafka** [comment]
After a bit of investigation:
- Config: 
` "jail_duration\":86400` ( One day )
`"block_signing_window\":360,\"missed_block_threshold\":180 `
(Missing out 180 blocks in the last 360 blocks)

- So the staking address was `| Jailed Until    | 2020-02-02 19:22:30 +08:00 | `
It implies that it was jailed  on | 2020-02-01 19:22:30 +08:00 | (Block [#52163](https://chain.crypto.com/explorer/blocks/52163) )

- Assuming it went total offline and push it backward for 180 blocks, It will be block [#51983](https://chain.crypto.com/explorer/blocks/51983), you can see that the validator `5F3ACF27F84ECFA5BF7D721FAE146DA70C52FA49` went offline after block 51983 (See block [#51984](https://chain.crypto.com/explorer/blocks/51984) ) 

- But then when I check its voting power at block 51983, I got `"voting_power": "1"` for this validator?

**Comment by lezzokafka** [comment]
Another observation: 

`5F3ACF27F84ECFA5BF7D721FAE146DA70C52FA49` joined (or rejoin) with `"voting_power": "1"`
 at block#51595.

**Comment by tomtau** [comment]
> Another observation:
> 
> `5F3ACF27F84ECFA5BF7D721FAE146DA70C52FA49` joined (or rejoin) with `"voting_power": "1"`
> at block#51595.

the rejoin may be due to the reward distribution

**Comment by yihuang** [comment]
> > Another observation:
> > `5F3ACF27F84ECFA5BF7D721FAE146DA70C52FA49` joined (or rejoin) with `"voting_power": "1"`
> > at block#51595.
> 
> the rejoin may be due to the reward distribution

So it's unbonding (quit validator), reward distribution (join validator), liveness_tracker re-initialized, non-live jailed?

**Comment by lezzokafka** [comment]
> > 
> > 
> > the rejoin may be due to the reward distribution
> 
> So it's unbonding (quit validator), reward distribution (join validator), liveness_tracker re-initialized, non-live jailed?

Can confirm that there was reward distribution at block 51595, seems this will trigger an update of the list.

**Comment by yihuang** [comment]
> > > the rejoin may be due to the reward distribution
> > 
> > 
> > So it's unbonding (quit validator), reward distribution (join validator), liveness_tracker re-initialized, non-live jailed?
> 
> Can confirm that there was reward distribution at block 51595, seems this will trigger an update of the list.

If this is the case, it's the same problem as the last one, reward distribution cause invalidator becomes active. So it's already fixed I guess.

**Comment by tomtau** [comment]
and 0 slash amount is due to Milli calculations?

**Comment by yihuang** [comment]
> and 0 slash amount is due to Milli calculations?

Probably since `voting_power == 1`.

**Comment by yihuang** [comment]
Procedure:
- Start three-node devnet (set reward period to a short amount of time).
- unbond all of node2, and stop node2.
- Expected correct behavior:
  - node2 is not validator again, no slash, bonded becomes zero.
- Wrong behavior:
  - node2 is still validator with a small amount of bonded coins and voting power.
  - because the node is stopped, it will be slashed with non-live fault, with `slash_amount==0`.

Test result:
- If we don't clear `proposer_stats` when node quits (v0.2.1), it definitely happens.
- With the current master branch, it can also happens in two situations:
  - Between the coping of the number of the boned coins and execution of the unbond tx, rewarding happen, causes there are unbonded coins left after unbonding.
  - Even we have an `unbond_all` tx type, if the tx is executed in the same block as rewarding, it still can happen.
  - It's still possible for node2 to become the proposer of the next block after the `end_block` when it stops to become a validator, which will cause it to appear in `proposer_stats` again, and get rewards. (speculated, not verified)

**Comment by yihuang** [comment]
Regarding the `slash_amount==0` problem, in my test, the state of staking address is like:
```
address:       0x33fab1769b286ca57f9bf05d1b4ba65998d008ee
bonded:        4854050710
council_node:  {"consensus_pubkey": {"type": "tendermint/PubKeyEd25519", "value": "SDA1zRMFUtkFZKwAar3aEa0CJQasro/6/kDV2rpAPsU="}, "name": "node2", "security_contact": "node2@example.com"}
nonce:         3
punishment:    {"jailed_until": 1581903128, "kind": "NonLive", "slash_amount": "0"}
unbonded:      90000000000000000
unbonded_from: 1581903017
```

It seems problematic.

**Comment by tomtau** [comment]
> unbond all of node2, and stop node2.
are they done at the same time or is it -- "unbond all coins, wait for the tx to be confirmed, stop node2"?

**Comment by yihuang** [comment]
> > unbond all of node2, and stop node2.
> 
> are they done at the same time or is it -- "unbond all coins, wait for the tx to be confirmed, stop node2"?

"wait for the tx to be confirmed" is not required, but it would make the test more stable.

**Comment by yihuang** [comment]
- After copy of the bonded amounts and before sending the unbond tx, rewarding can happen, so there are bonded coins remained after unbonding.
- Even if we have an unbond_all tx type, if the tx is executed in the same block as rewarding, it still can happen.

The above two points are hard to avoid, so an operator should be careful to re-check the staking state after unbonding, to confirm there are zero bonded coins, then stop the node.

- It's still possible for node2 to become the proposer of the next block after the end_block when it stops to become a validator, which will cause it to appear in proposer_stats again, and get rewards. (speculated, not verified)

Check validator is not inactivated in rewards_record_proposer.

**Comment by tomtau** [comment]
> Even if we have an unbond_all tx type, if the tx is executed in the same block as rewarding, it still can happen.

wouldn't that transaction fail? As the validator would sign a transaction against a staked state with nonce N, but after the reward distribution, the staked state's nonce should be N+1?

**Comment by yihuang** [comment]
> > Even if we have an unbond_all tx type, if the tx is executed in the same block as rewarding, it still can happen.
> 
> wouldn't that transaction fail? As the validator would sign a transaction against a staked state with nonce N, but after the reward distribution, the staked state's nonce should be N+1?

Oh, yes, it would fail because reward distribution happens in `begin_block`, and the nonce would not match in `deliver_tx`. (So this implies in the block of reward distribution, all the transactions dealing with validator's staking address will fail?)

**Comment by lezzokafka** [comment]
>....
> * unbond all of node2, and stop node2.

>....
> * Wrong behavior:
>   * node2 is still validator with a small amount of bonded coins and voting power.

Just want to to check if I understand it correctly: 
- The remaining small amount (which turned out becoming the voting power) is due to some remaining tokens in the _bonded_ account, which can not be unbonded at the current setting without introducing a new  `unbond_all tx` type. 

> Setting `required_council_node_stake > share_of_rewarding_of_the_node` helps, even if the node gets rewarded after unbond, it doesn't have enough coins to become validator again. But the value of `share_of_rewarding_of_the_node` is dynamic.

- If a validator bonded amount is sitting on the edge of the `required_council_node_stake` and unbonded an `amount` that's less then `share_of_rewarding_of_the_node`. When the reward comes in, would similar issue happen due to the validator would have enough tokens and back in the game?

**Comment by yihuang** [comment]
The reason for the `slash_amount=0` problem, is when `validator_voting_percent` is small enough, the computed `slashing_proportion` is zero, and since `slash_ratio` will be multiplied with it, it becomes zero too.
```
validator_voting_percent = faulting_validator_voting_power / total_staking
```
It didn't take into account unbonded coins, so if a validator make a fault and unbond most of the coins,  he can escape the punishment(not verified yet).

**Comment by yihuang** [comment]
> > ....
> > 
> > * unbond all of node2, and stop node2.
> 
> > ....
> > 
> > * Wrong behavior:
> >   
> >   * node2 is still validator with a small amount of bonded coins and voting power.
> 
> Just want to to check if I understand it correctly:
> 
> * The remaining small amount (which turned out becoming the voting power) is due to some remaining tokens in the _bonded_ account (or it is the reward to the bonded account?), which can not be unbonded at the current setting without introducing a new  `unbond_all` tx type.

It's newly added rewards, and if the operator is not careful to check it again, and stop the node directly, non-live fault will happen.

> 
> > Setting `required_council_node_stake > share_of_rewarding_of_the_node` helps, even if the node gets rewarded after unbond, it doesn't have enough coins to become validator again. But the value of `share_of_rewarding_of_the_node` is dynamic.
> 
> * If a validator bonded amount is sitting on the edge of the `required_council_node_stake`, and he unbonded an `amount` that's less then `share_of_rewarding_of_the_node`. When the reward comes in, would similar issue happen due to the validator would have enough tokens and back in the game?

Yes.
`nonce` checking and `unbond_all` tx type can help with this problem.

**Comment by yihuang** [comment]
Summary current situation:
- proportion calculation issue opened separated as #1096, I think it's to be solved after new punishment spec work?
- Remaining bonded coins after unbonding, and the non-live fault because of it, small issue.
  - The operator can be more careful to double-check after unbonding, and do it again if there are remaining bonded coins.
  - Even if it happens, only affect a small amount of coins.

**Comment by yihuang** [comment]
Summary current situation:
- proportion calculation issue opened separated as #1096, I think it's to be solved after new punishment spec work?
- Remaining bonded coins after unbonding, and the non-live fault because of it, small issue.
  - The operator can be more careful to double-check after unbonding, and do it again if there are remaining bonded coins.
  - Even if it happens, only affect a small amount of coins.

**Comment by tomtau** [comment]
probably not relevant after https://github.com/crypto-com/chain/pull/1292  ?
