### ISSUE TITLE
JavaSDK

### ISSUE THREAD

**Issue by ADiligentMan** [crypto-com/chain#1284]
**Describe the solution you'd like**
I want to have a Java SDK

**Comment by tomtau** [comment]
@ADiligentMan thanks for your feature request -- there's a related issue that will be a building block for the later SDK: https://github.com/crypto-com/chain/issues/1236 

Most likely, Java/Kotlin SDK will evolve in a separate repository (similarly to https://github.com/crypto-com/cro-nodelib ), so will close this issue here for now
