### ISSUE TITLE
Problem: light client doesn't verify the fetched staking state

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#1313]
1. abci query when "proof=true" should return the inclusion proof for the queried state: https://docs.tendermint.com/master/spec/abci/abci.html#query validators don't need to store this, but full nodes for (historical) querying may need to extend the storage of app_hash=>height, app_hash=>(height, trie root) unless it's already done
2. light client should keep track of the state trie root (and app hash?) from sync, so that it can verify the inclusion proof

**Comment by yihuang** [comment]
Proposal:

- Query staking state with client-rpc/client-cli, need to provide wallet name, and only query staking state at the block height of recent sync, and verify the proof against the sync state. Rather than query the the most recent state or arbitrary historical state.
- If you want to query staking at arbitrary historical block height or most recent height, you can simply call abci_query directly, if you want to verify the proof in this case, you need to do it on your own (get a trusted merkle root hash first).

**Comment by leejw51crypto** [comment]
but verification needs whole trie,
how about delegating to the full node?

**Comment by yihuang** [comment]
> but verification needs whole trie,
> how about delegating to the full node?

It verifies the Merkel proof against the root hash in chain state.

**Comment by tomtau** [comment]
> but verification needs whole trie,
> how about delegating to the full node?

it doesn't need it -- that's the point of a "light client"... It only needs to know the validator set + "root" (embedded in app hash) and be given the merkle proof from the leaf to the root
