### ISSUE TITLE
Problem: client sync fails if TM is catching up with the network

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#831]
Some RPC endpoints (e.g. /validators) may not return the latest or historical information if TM node is not yet fully sync (didn't catch up with the network's latest block). as observed with @lezzokafka 

It'll be good if client could check `/status` endpoint before running sync, as otherwise it may fail with a confusing error message

**Comment by yihuang** [comment]
Strange, wallet syncing always start with a `status` call, and only sync to the latest_height returned. Is it easy to reproduce?

**Comment by lezzokafka** [comment]
@yihuang  
Yaa
For example, when joining a network with current block heigh of 100k, 
start the tendermint node and so on to sync blocks. While it is syncing, the sync will fail because it is still trying to catch up with the network. 
  
Similar issue with the tendermint rpc as well, say you have synced from block #1 to block #100, and it is still catching up with  the network, when you do something like `http://localhost:26657/block?height=50` to check block#50, the will be an error message with something like 
"Height must be less than or equal to the current blockchain height."

**Comment by leejw51crypto** [comment]
is there any possible to ask blocks bigger than current height
which is received from status?

**Comment by yihuang** [comment]
I reproduced, we are not requesting data with a height bigger the `latest_height` reported by `status`, I guess it's just not stable when tendermint catching up, maybe we should hold wallet syncing when tendermint catching up.
