### ISSUE TITLE
Problem: no integration test for new validator join tx

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#852]
@leejw51crypto Jason can help with this issue

**Comment by leejw51crypto** [comment]
it's done, preparing pr now.
because i couldn't make transfer-utxo work as intended, it took some time.
but after rebase, transfer-utxo was solved.

also there is sync-related glitch, by which, i couldn't make join tx valid.
that was broken tendermint rust type deserialzation, that was solved by huang yi.

after above fix, now joining tx works now.

**Comment by tomtau** [comment]
resolved by https://github.com/crypto-com/chain/pull/932
