### ISSUE TITLE
Problem: client-* assumes all key pairs / wallets to be in a local storage

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain#961]
For HW wallet support, this won't be the case -- client will be exposed public keys (upon authorisation on the device) / addresses, but signing will be external

**Comment by yihuang** [comment]
Is the watch-only wallet usable with HW wallet?

**Comment by tomtau** [comment]
> Is the watch-only wallet usable with HW wallet?

There are two options for that:

1. "mixed" storage wallet -- spending key pairs are managed by the device, view keys by the client local app

2. "delayed" sync -- the client accumulates / keeps track of transaction IDs... the tx-query flows are execution in a batch after the user's explicit command and confirming the request signing on the device

maybe option 1. is easier?

**Comment by yihuang** [comment]
> > Is the watch-only wallet usable with HW wallet?
> 
> There are two options for that:
> 
> 1. "mixed" storage wallet -- spending key pairs are managed by the device, view keys by the client local app
> 2. "delayed" sync -- the client accumulates / keeps track of transaction IDs... the tx-query flows are execution in a batch after the user's explicit command and confirming the request signing on the device
> 
> maybe option 1. is easier?

Current watch-only wallet is similar to the option  1.  The user provides the view key pair and public keys of addresses, and able to sync the wallet.

**Comment by tomtau** [comment]
for reference -- one project with some functionality similar to "client-*" for ETC that supports local file-based signing and external HW device signing: https://github.com/emeraldpay/emerald-vault/blob/master/src/structs/wallet.rs#L129

**Comment by leejw51crypto** [comment]
options 1 easier

**Comment by linfeng-crypto** [comment]
hardware wallet will use the same signature algorithm, but it won't work in the same way the current code "assumes" it -- the current code does:
* local: constructs tx
* local: computes txid
* local: signs on the txid 

with hw wallet, it'll be:
* local: constructs tx
* local<->external: send tx data + a part of HD-path (so that the HW wallet knows which private key to use) and wait for response
* (user action -- yes/no -- on the device)
* external: computes txid
* external: signs on the txid
* local<->external: sends back the signature
